// ============================================================================
// Dummy data ("seed") voor het prototype.
// ----------------------------------------------------------------------------
// Alles is verzonnen maar realistisch voor Prefab Select. De Zustand-store
// initialiseert hiermee; later vervangt Supabase deze seed.
// ============================================================================

import type {
  Appointment,
  AppNotification,
  Integration,
  Invoice,
  Lead,
  Note,
  Payment,
  Quote,
  QuoteEmailLog,
  QuoteRequest,
  ReminderRule,
  Task,
  TaskComment,
  UploadedFile,
  User,
} from "./types";
import { DEFAULT_BTW, DEFAULT_VOORWAARDEN } from "./constants";

// Datums relatief t.o.v. nu, zodat het dashboard altijd "levend" oogt.
function dag(offset: number, uur = 9, minuut = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  d.setHours(uur, minuut, 0, 0);
  return d.toISOString();
}

export const seedLeads: Lead[] = [
  {
    id: "lead-001",
    naam: "Familie De Vries",
    email: "devries@gmail.com",
    telefoon: "06-21345678",
    adres: "Molenweg 12",
    plaats: "Middelburg",
    postcode: "4331 AB",
    stage: "nieuwe_lead",
    source: "website_formulier",
    product: "mantelzorgwoning",
    waarde: 89000,
    kans: 20,
    toegewezenAan: "Kelly",
    tags: ["zeeland", "spoed"],
    bericht: "Wij zoeken een mantelzorgwoning voor mijn moeder, het liefst dit jaar nog.",
    aangemaaktOp: dag(-1, 14, 12),
    laatsteActiviteit: dag(-1, 14, 12),
    positie: 0,
  },
  {
    id: "lead-002",
    naam: "Jeroen Bakker",
    email: "j.bakker@outlook.com",
    telefoon: "06-44112233",
    plaats: "Goes",
    stage: "nieuwe_lead",
    source: "meta_ads",
    product: "tuinkantoor",
    waarde: 24000,
    kans: 15,
    toegewezenAan: "Tom",
    tags: ["thuiswerken"],
    bericht: "Interesse in een tuinkantoor van ca. 20m².",
    aangemaaktOp: dag(0, 8, 30),
    laatsteActiviteit: dag(0, 8, 30),
    positie: 1,
  },
  {
    id: "lead-003",
    naam: "Sandra Pietersen",
    email: "s.pietersen@ziggo.nl",
    telefoon: "06-19283746",
    plaats: "Vlissingen",
    stage: "offerte_opgenomen",
    source: "configurator",
    product: "prefab_aanbouw",
    waarde: 56000,
    kans: 35,
    toegewezenAan: "Kelly",
    tags: ["configurator"],
    bericht: "Configuratie afgerond: aanbouw 6x4m met dakraam.",
    aangemaaktOp: dag(-3, 11, 0),
    laatsteActiviteit: dag(-1, 9, 45),
    positie: 0,
  },
  {
    id: "lead-004",
    naam: "Bouwbedrijf Janssen BV",
    bedrijf: "Janssen Bouw",
    email: "info@janssenbouw.nl",
    telefoon: "0118-556677",
    plaats: "Terneuzen",
    stage: "offerte_opgenomen",
    source: "referral",
    product: "schuur",
    waarde: 41000,
    kans: 40,
    toegewezenAan: "Mark",
    tags: ["zakelijk", "b2b"],
    aangemaaktOp: dag(-4, 16, 20),
    laatsteActiviteit: dag(-2, 13, 0),
    positie: 1,
  },
  {
    id: "lead-005",
    naam: "Familie Mulder",
    email: "mulder.familie@gmail.com",
    telefoon: "06-55667788",
    plaats: "Kapelle",
    stage: "gebeld_3x",
    source: "google_ads",
    product: "poolhouse",
    waarde: 72000,
    kans: 45,
    toegewezenAan: "Sanne",
    tags: ["premium"],
    aangemaaktOp: dag(-6, 10, 0),
    laatsteActiviteit: dag(-1, 15, 30),
    positie: 0,
  },
  {
    id: "lead-006",
    naam: "Peter van Damme",
    email: "pvandamme@kpnmail.nl",
    telefoon: "06-33221100",
    plaats: "Zierikzee",
    stage: "gebeld_3x",
    source: "website_formulier",
    product: "prefab_uitbouw",
    waarde: 38000,
    kans: 40,
    toegewezenAan: "Tom",
    tags: [],
    aangemaaktOp: dag(-8, 9, 0),
    laatsteActiviteit: dag(-2, 11, 15),
    positie: 1,
  },
  {
    id: "lead-007",
    naam: "Familie El Amrani",
    email: "elamrani@gmail.com",
    telefoon: "06-77889900",
    plaats: "Bergen op Zoom",
    stage: "afspraak_ingepland",
    source: "meta_ads",
    product: "mantelzorgwoning",
    waarde: 95000,
    kans: 55,
    toegewezenAan: "Kelly",
    tags: ["spoed", "premium"],
    aangemaaktOp: dag(-10, 12, 0),
    laatsteActiviteit: dag(0, 9, 0),
    positie: 0,
  },
  {
    id: "lead-008",
    naam: "Linda Hoogendoorn",
    email: "l.hoogendoorn@hotmail.com",
    telefoon: "06-12121212",
    plaats: "Roosendaal",
    stage: "afspraak_ingepland",
    source: "configurator",
    product: "chalet",
    waarde: 64000,
    kans: 50,
    toegewezenAan: "Sanne",
    tags: ["recreatie"],
    aangemaaktOp: dag(-12, 14, 0),
    laatsteActiviteit: dag(-1, 16, 0),
    positie: 1,
  },
  {
    id: "lead-009",
    naam: "Familie Smit",
    email: "smit.recreatie@gmail.com",
    telefoon: "06-98765432",
    plaats: "Renesse",
    stage: "offerte_verstuurd",
    source: "website_formulier",
    product: "vakantiewoning",
    waarde: 118000,
    kans: 60,
    toegewezenAan: "Mark",
    tags: ["recreatie", "premium"],
    aangemaaktOp: dag(-15, 10, 0),
    laatsteActiviteit: dag(-2, 10, 30),
    positie: 0,
  },
  {
    id: "lead-010",
    naam: "Karin de Groot",
    email: "kdegroot@gmail.com",
    telefoon: "06-45454545",
    plaats: "Tholen",
    stage: "offerte_verstuurd",
    source: "google_ads",
    product: "prefab_aanbouw",
    waarde: 49000,
    kans: 55,
    toegewezenAan: "Kelly",
    tags: [],
    aangemaaktOp: dag(-18, 9, 30),
    laatsteActiviteit: dag(-3, 14, 0),
    positie: 1,
  },
  {
    id: "lead-011",
    naam: "Familie Visser",
    email: "visser@home.nl",
    telefoon: "06-32132132",
    plaats: "Breda",
    stage: "offerte_akkoord",
    source: "referral",
    product: "poolhouse",
    waarde: 81000,
    kans: 90,
    toegewezenAan: "Sanne",
    tags: ["premium"],
    aangemaaktOp: dag(-25, 11, 0),
    laatsteActiviteit: dag(-1, 11, 0),
    positie: 0,
  },
  {
    id: "lead-012",
    naam: "Robert Maas",
    email: "r.maas@gmail.com",
    telefoon: "06-65656565",
    plaats: "Oosterhout",
    stage: "tekeningen_maken",
    source: "configurator",
    product: "tuinkantoor",
    waarde: 28000,
    kans: 100,
    toegewezenAan: "Tom",
    tags: ["thuiswerken"],
    aangemaaktOp: dag(-40, 10, 0),
    laatsteActiviteit: dag(-4, 9, 0),
    positie: 0,
  },
  {
    id: "lead-013",
    naam: "Familie Koning",
    email: "koning.familie@gmail.com",
    telefoon: "06-78787878",
    plaats: "Etten-Leur",
    stage: "facturen_verstuurd",
    source: "website_formulier",
    product: "prefab_uitbouw",
    waarde: 43000,
    kans: 100,
    toegewezenAan: "Mark",
    tags: [],
    aangemaaktOp: dag(-60, 10, 0),
    laatsteActiviteit: dag(-7, 12, 0),
    positie: 0,
  },
  {
    id: "lead-014",
    naam: "Familie Willems",
    email: "willems@xs4all.nl",
    telefoon: "06-90909090",
    plaats: "Goes",
    stage: "opdracht_afgerond",
    source: "meta_ads",
    product: "mantelzorgwoning",
    waarde: 92000,
    kans: 100,
    toegewezenAan: "Kelly",
    tags: ["premium", "review"],
    aangemaaktOp: dag(-80, 10, 0),
    laatsteActiviteit: dag(-10, 12, 0),
    positie: 0,
  },
  {
    id: "lead-015",
    naam: "Henk Dijkstra",
    email: "h.dijkstra@gmail.com",
    telefoon: "06-10101010",
    plaats: "Hulst",
    stage: "offerte_afgewezen",
    source: "google_ads",
    product: "chalet",
    waarde: 58000,
    kans: 0,
    toegewezenAan: "Sanne",
    tags: ["budget"],
    bericht: "Uiteindelijk voor een lokale aannemer gekozen.",
    aangemaaktOp: dag(-35, 10, 0),
    laatsteActiviteit: dag(-12, 9, 0),
    positie: 0,
  },
];

export const seedNotes: Note[] = [
  { id: "note-1", leadId: "lead-001", type: "systeem", tekst: "Lead aangemaakt via website formulier.", auteur: "Systeem", aangemaaktOp: dag(-1, 14, 12) },
  { id: "note-2", leadId: "lead-005", type: "telefoon", tekst: "Gebeld — wil graag de showroom bezoeken. Belt terug voor datum.", auteur: "Sanne", aangemaaktOp: dag(-1, 15, 30) },
  { id: "note-3", leadId: "lead-007", type: "telefoon", tekst: "Intakegesprek gepland voor volgende week. Zeer geïnteresseerd, budget akkoord.", auteur: "Kelly", aangemaaktOp: dag(0, 9, 0) },
  { id: "note-4", leadId: "lead-009", type: "email", tekst: "Offerte verstuurd via Resend. Klant bevestigt ontvangst.", auteur: "Mark", aangemaaktOp: dag(-2, 10, 30) },
  { id: "note-5", leadId: "lead-011", type: "notitie", tekst: "Akkoord op offerte! Aanbetaling 30% afgesproken. Productie kan starten zodra vergunning rond is.", auteur: "Sanne", aangemaaktOp: dag(-1, 11, 0) },
];

export const seedUsers: User[] = [
  { id: "u-kelly", naam: "Kelly", email: "kelly@prefabselect.nl", rol: "eigenaar", kleur: "#2563eb", googleConnected: true },
  { id: "u-mark", naam: "Mark", email: "mark@prefabselect.nl", rol: "verkoop", kleur: "#10b981", googleConnected: false },
  { id: "u-sanne", naam: "Sanne", email: "sanne@prefabselect.nl", rol: "verkoop", kleur: "#8b5cf6", googleConnected: true },
  { id: "u-tom", naam: "Tom", email: "tom@prefabselect.nl", rol: "werkvoorbereiding", kleur: "#f59e0b", googleConnected: false },
  { id: "u-lisa", naam: "Lisa", email: "lisa@prefabselect.nl", rol: "administratie", kleur: "#06b6d4", googleConnected: false },
];

export const seedTasks: Task[] = [
  { id: "task-1", leadId: "lead-001", titel: "Familie De Vries terugbellen", omschrijving: "Eerste contact, behoefte inventariseren", deadline: dag(0, 11, 0), prioriteit: "hoog", medewerkerId: "u-kelly", status: "open", reminderMinuten: 30, aangemaaktOp: dag(-1, 14, 12) },
  { id: "task-2", leadId: "lead-003", quoteId: undefined, titel: "Offerte opstellen aanbouw", deadline: dag(1, 9, 0), prioriteit: "normaal", medewerkerId: "u-kelly", status: "bezig", reminderMinuten: 60, aangemaaktOp: dag(-2, 10, 0) },
  { id: "task-3", leadId: "lead-005", titel: "Showroomafspraak inplannen", deadline: dag(-1, 16, 0), prioriteit: "normaal", medewerkerId: "u-sanne", status: "open", reminderMinuten: null, aangemaaktOp: dag(-3, 9, 0) },
  { id: "task-4", leadId: "lead-009", quoteId: "quote-1", titel: "Offerte opvolgen — bellen", omschrijving: "Offerte staat 2 dagen open", deadline: dag(1, 14, 0), prioriteit: "hoog", medewerkerId: "u-mark", status: "wachten", reminderMinuten: 15, aangemaaktOp: dag(-2, 11, 0) },
  { id: "task-5", leadId: "lead-012", projectId: "lead-012", titel: "Productieplanning bevestigen", deadline: dag(3, 10, 0), prioriteit: "normaal", medewerkerId: "u-tom", status: "bezig", reminderMinuten: null, aangemaaktOp: dag(-4, 9, 0) },
  { id: "task-6", leadId: "lead-011", quoteId: "quote-3", titel: "Aanbetaling factureren", deadline: dag(2, 9, 0), prioriteit: "hoog", medewerkerId: "u-lisa", status: "open", reminderMinuten: 60, aangemaaktOp: dag(-1, 11, 0) },
  { id: "task-7", titel: "Wekelijkse pipeline-review met team", deadline: dag(2, 16, 0), prioriteit: "laag", medewerkerId: "u-kelly", status: "open", reminderMinuten: null, aangemaaktOp: dag(-2, 8, 0) },
  { id: "task-8", leadId: "lead-014", titel: "Review vragen aan familie Willems", deadline: dag(-2, 10, 0), prioriteit: "laag", medewerkerId: "u-kelly", status: "gereed", reminderMinuten: null, aangemaaktOp: dag(-5, 10, 0) },
];

export const seedTaskComments: TaskComment[] = [
  { id: "tc-1", taskId: "task-2", auteurId: "u-kelly", tekst: "Configuratie ontvangen, ik begin met de calculatie.", aangemaaktOp: dag(-1, 10, 0) },
  { id: "tc-2", taskId: "task-4", auteurId: "u-mark", tekst: "Voicemail ingesproken, wacht op terugbelverzoek.", aangemaaktOp: dag(0, 9, 30) },
  { id: "tc-3", taskId: "task-5", auteurId: "u-tom", tekst: "Productieslot week 14 gereserveerd onder voorbehoud.", aangemaaktOp: dag(-1, 15, 0) },
];

export const seedAppointments: Appointment[] = [
  { id: "afspr-1", leadId: "lead-007", titel: "Adviesgesprek familie El Amrani", type: "adviesgesprek", start: dag(2, 10, 0), eind: dag(2, 11, 0), locatie: "Bij klant thuis, Bergen op Zoom", omschrijving: "Mantelzorgwoning bespreken", medewerkerId: "u-kelly", googleSynced: true },
  { id: "afspr-2", leadId: "lead-008", titel: "Offertebespreking Linda Hoogendoorn", type: "offertebespreking", start: dag(3, 14, 0), eind: dag(3, 15, 30), locatie: "Showroom Prefab Select", medewerkerId: "u-sanne", googleSynced: true },
  { id: "afspr-3", leadId: "lead-011", quoteId: "quote-3", titel: "Inmeten familie Visser", type: "inmeten", start: dag(5, 9, 0), eind: dag(5, 11, 0), locatie: "Breda", omschrijving: "Opmeten + grond inspecteren", medewerkerId: "u-tom", googleSynced: false },
  { id: "afspr-4", leadId: "lead-013", titel: "Oplevering familie Koning", type: "oplevering", start: dag(7, 13, 0), eind: dag(7, 14, 0), locatie: "Etten-Leur", medewerkerId: "u-tom", googleSynced: true },
  { id: "afspr-5", leadId: "lead-005", titel: "Telefonisch gesprek familie Mulder", type: "telefonisch", start: dag(1, 11, 0), eind: dag(1, 11, 30), medewerkerId: "u-sanne", googleSynced: false },
  { id: "afspr-6", leadId: "lead-012", titel: "Plaatsing tuinkantoor Robert Maas", type: "plaatsing", start: dag(4, 8, 0), eind: dag(4, 16, 0), locatie: "Oosterhout", omschrijving: "Plaatsing in 1 dag", medewerkerId: "u-tom", googleSynced: false },
  { id: "afspr-7", leadId: "lead-004", titel: "Werkvoorbereiding Janssen Bouw", type: "werkvoorbereiding", start: dag(0, 13, 0), eind: dag(0, 14, 0), locatie: "Kantoor", medewerkerId: "u-tom", googleSynced: false },
];

export const seedFiles: UploadedFile[] = [
  { id: "file-1", leadId: "lead-003", naam: "configuratie-aanbouw.pdf", type: "pdf", grootteKb: 842, geuploadOp: dag(-3, 11, 5), geuploadDoor: "Systeem" },
  { id: "file-2", leadId: "lead-009", naam: "offerte-PS-2026-0009.pdf", type: "pdf", grootteKb: 1240, geuploadOp: dag(-2, 10, 30), geuploadDoor: "Mark" },
  { id: "file-3", leadId: "lead-011", naam: "situatieschets-tuin.jpg", type: "afbeelding", grootteKb: 3120, geuploadOp: dag(-5, 14, 0), geuploadDoor: "Sanne" },
  { id: "file-4", leadId: "lead-011", naam: "vergunning-aanvraag.pdf", type: "pdf", grootteKb: 560, geuploadOp: dag(-3, 9, 0), geuploadDoor: "Sanne" },
];

export const seedQuoteRequests: QuoteRequest[] = [
  { id: "aanvr-1", leadId: "lead-003", source: "configurator", product: "prefab_aanbouw", omschrijving: "Aanbouw 6x4m met plat dak en groot dakraam, inclusief afwerking keukenblok.", budgetIndicatie: 55000, gewensteOpleverdatum: dag(120), status: "in_behandeling", ontvangenOp: dag(-3, 11, 0) },
  { id: "aanvr-2", leadId: "lead-004", source: "referral", product: "schuur", omschrijving: "Bedrijfsschuur 10x6m voor opslag materiaal.", budgetIndicatie: 40000, status: "in_behandeling", ontvangenOp: dag(-4, 16, 20) },
  { id: "aanvr-3", leadId: "lead-002", source: "meta_ads", product: "tuinkantoor", omschrijving: "Tuinkantoor ca. 20m², geïsoleerd, met elektra.", budgetIndicatie: 24000, status: "nieuw", ontvangenOp: dag(0, 8, 30) },
  { id: "aanvr-4", leadId: "lead-009", source: "website_formulier", product: "vakantiewoning", omschrijving: "Recreatiewoning ca. 60m² voor verhuur in Renesse.", budgetIndicatie: 115000, status: "omgezet", ontvangenOp: dag(-15, 10, 0) },
  { id: "aanvr-5", leadId: "lead-001", source: "website_formulier", product: "mantelzorgwoning", omschrijving: "Mantelzorgwoning voor moeder, gelijkvloers, ca. 50m².", budgetIndicatie: 89000, gewensteOpleverdatum: dag(180), status: "nieuw", ontvangenOp: dag(-1, 14, 12) },
];

export const seedQuotes: Quote[] = [
  {
    id: "quote-1",
    nummer: "PS-2026-0009",
    leadId: "lead-009",
    status: "verstuurd",
    projecttype: "vakantiewoning",
    projectomschrijving: "Recreatiewoning voor verhuur op een park in Renesse. Energiezuinige prefab woning, instapklaar opgeleverd.",
    afmetingen: "10 x 6 m, vloeroppervlak ca. 60 m², nokhoogte 4,5 m",
    werkzaamheden: "Productie casco, transport, plaatsing op bestaande fundering, complete afwerking interieur en aansluiten installaties.",
    regels: [
      { id: "r1", omschrijving: "Vakantiewoning prefab casco 60m²", aantal: 1, eenheid: "stuks", prijsPerStuk: 78000, btwPercentage: DEFAULT_BTW },
      { id: "r2", omschrijving: "Complete afwerking interieur", aantal: 1, eenheid: "post", prijsPerStuk: 24000, btwPercentage: DEFAULT_BTW },
      { id: "r3", omschrijving: "Fundering & plaatsing", aantal: 1, eenheid: "post", prijsPerStuk: 12000, btwPercentage: DEFAULT_BTW },
    ],
    korting: 0,
    geldigTot: dag(25),
    notitie: "Levertijd ca. 16 weken na akkoord en vergunning.",
    voorwaarden: DEFAULT_VOORWAARDEN,
    aangemaaktOp: dag(-3, 10, 0),
    verstuurdOp: dag(-2, 10, 30),
  },
  {
    id: "quote-2",
    nummer: "PS-2026-0010",
    leadId: "lead-010",
    status: "bekeken",
    projecttype: "prefab_aanbouw",
    projectomschrijving: "Aanbouw aan de achterzijde van de woning ter vergroting van de woonkamer.",
    afmetingen: "5 x 4 m, vloeroppervlak 20 m², plat dak",
    werkzaamheden: "Productie en plaatsing prefab aanbouw casco, dakraam, isolatie en afwerking.",
    regels: [
      { id: "r1", omschrijving: "Prefab aanbouw 5x4m casco", aantal: 1, eenheid: "stuks", prijsPerStuk: 34000, btwPercentage: DEFAULT_BTW },
      { id: "r2", omschrijving: "Dakraam + extra isolatie", aantal: 1, eenheid: "post", prijsPerStuk: 6500, btwPercentage: DEFAULT_BTW },
      { id: "r3", omschrijving: "Plaatsing & afwerking", aantal: 1, eenheid: "post", prijsPerStuk: 8500, btwPercentage: DEFAULT_BTW },
    ],
    korting: 1000,
    geldigTot: dag(22),
    voorwaarden: DEFAULT_VOORWAARDEN,
    aangemaaktOp: dag(-4, 9, 0),
    verstuurdOp: dag(-3, 14, 0),
    bekekenOp: dag(-2, 18, 12),
  },
  {
    id: "quote-3",
    nummer: "PS-2026-0011",
    leadId: "lead-011",
    status: "geaccepteerd",
    projecttype: "poolhouse",
    projectomschrijving: "Vrijstaand poolhouse met overkapping en technische ruimte naast het zwembad.",
    afmetingen: "8 x 5 m, vloeroppervlak 40 m², incl. overkapping 3 m",
    werkzaamheden: "Productie, transport, fundering, plaatsing, sanitair en technische ruimte volledig aangesloten.",
    planning: "Start productie ca. 4 weken na akkoord · plaatsing in week 12 · oplevering in week 14 (indicatief, onder voorbehoud van vergunning).",
    regels: [
      { id: "r1", omschrijving: "Poolhouse 8x5m incl. overkapping", aantal: 1, eenheid: "stuks", prijsPerStuk: 62000, btwPercentage: DEFAULT_BTW },
      { id: "r2", omschrijving: "Sanitair & technische ruimte", aantal: 1, eenheid: "post", prijsPerStuk: 14000, btwPercentage: DEFAULT_BTW },
      { id: "r3", omschrijving: "Plaatsing & fundering", aantal: 1, eenheid: "post", prijsPerStuk: 9000, btwPercentage: DEFAULT_BTW },
    ],
    korting: 4000,
    geldigTot: dag(10),
    notitie: "Aanbetaling 30% bij akkoord.",
    voorwaarden: DEFAULT_VOORWAARDEN,
    aangemaaktOp: dag(-7, 11, 0),
    verstuurdOp: dag(-6, 9, 0),
    bekekenOp: dag(-5, 20, 0),
    beslistOp: dag(-1, 11, 0),
  },
];

export const seedEmailLogs: QuoteEmailLog[] = [
  { id: "mail-1", quoteId: "quote-1", naar: "smit.recreatie@gmail.com", onderwerp: "Uw offerte van Prefab Select", status: "verzonden", messageId: "seed-0009", mock: true, verstuurdOp: dag(-2, 10, 30) },
  { id: "mail-2", quoteId: "quote-2", naar: "kdegroot@gmail.com", onderwerp: "Uw offerte van Prefab Select", status: "verzonden", messageId: "seed-0010", mock: true, verstuurdOp: dag(-3, 14, 0) },
  { id: "mail-3", quoteId: "quote-3", naar: "visser@home.nl", onderwerp: "Uw offerte van Prefab Select", status: "verzonden", messageId: "seed-0011", mock: true, verstuurdOp: dag(-6, 9, 0) },
];

export const seedIntegrations: Integration[] = [
  { id: "int-meta", naam: "Meta Ads", categorie: "marketing", verbonden: false, beschrijving: "Importeer leads & advertentieprestaties uit Facebook/Instagram." },
  { id: "int-ga", naam: "Google Analytics 4", categorie: "analytics", verbonden: false, beschrijving: "Websiteverkeer, conversies en bronnen koppelen." },
  { id: "int-gcal", naam: "Google Calendar", categorie: "agenda", verbonden: false, beschrijving: "Afspraken automatisch synchroniseren met je agenda." },
  { id: "int-resend", naam: "Resend", categorie: "email", verbonden: false, beschrijving: "Offertes en e-mails versturen vanuit het CRM." },
  { id: "int-form", naam: "Website formulier", categorie: "website", verbonden: true, beschrijving: "Contact- en offerteformulieren van prefabselect.nl.", laatsteSync: dag(0, 8, 30) },
  { id: "int-config", naam: "Configurator", categorie: "website", verbonden: true, beschrijving: "Leads uit de online product-configurator.", laatsteSync: dag(-1, 9, 45) },
];

export const seedNotifications: AppNotification[] = [
  { id: "notif-1", type: "nieuwe_lead", titel: "Nieuwe lead", tekst: "Jeroen Bakker via Meta Ads (tuinkantoor).", link: "/leads/lead-002", gelezen: false, voorUserId: "u-tom", aangemaaktOp: dag(0, 8, 30) },
  { id: "notif-2", type: "offerte_geaccepteerd", titel: "Offerte geaccepteerd", tekst: "Familie Visser accepteerde offerte PS-2026-0011.", link: "/offertes/quote-3", gelezen: false, voorUserId: "u-sanne", aangemaaktOp: dag(-1, 11, 0) },
  { id: "notif-3", type: "nieuwe_afspraak", titel: "Nieuwe afspraak", tekst: "Inmeten familie Visser ingepland.", link: "/agenda", gelezen: true, voorUserId: "u-tom", aangemaaktOp: dag(-1, 9, 0) },
  { id: "notif-4", type: "taak_verlopen", titel: "Taak verlopen", tekst: "Showroomafspraak inplannen (familie Mulder) is over de deadline.", link: "/taken", gelezen: false, voorUserId: "u-sanne", aangemaaktOp: dag(-1, 16, 0) },
];

export const seedReminderRules: ReminderRule[] = [
  { id: "rem-lead", trigger: "nieuwe_lead", label: "Nieuwe lead opvolgen", offsetDagen: 1, actief: true },
  { id: "rem-offerte", trigger: "offerte_verstuurd", label: "Verstuurde offerte opvolgen", offsetDagen: 7, actief: true },
  { id: "rem-afspraak", trigger: "afspraak_gepland", label: "Herinnering vóór afspraak", offsetUrenVooraf: 24, actief: true },
];

export const seedInvoices: Invoice[] = [
  {
    id: "inv-1", nummer: "FACT-2026-0001", leadId: "lead-011", quoteId: "quote-3",
    status: "verzonden", termijnLabel: "40% — aanbetaling bij opdracht",
    regels: [{ id: "ir1", omschrijving: "Aanbetaling 40% — Poolhouse (PS-2026-0011)", aantal: 1, eenheid: "post", prijsPerStuk: 32400, btwPercentage: DEFAULT_BTW }],
    korting: 0, vervaldatum: dag(-2), notitie: "Productie start na ontvangst van de aanbetaling.",
    aangemaaktOp: dag(-8, 10, 0), verstuurdOp: dag(-8, 10, 5),
  },
  {
    id: "inv-2", nummer: "FACT-2026-0002", leadId: "lead-011", quoteId: "quote-3",
    status: "verzonden", termijnLabel: "30% — bij aanvang productie",
    regels: [{ id: "ir1", omschrijving: "Termijn 30% — bij aanvang productie (PS-2026-0011)", aantal: 1, eenheid: "post", prijsPerStuk: 24300, btwPercentage: DEFAULT_BTW }],
    korting: 0, vervaldatum: dag(6),
    aangemaaktOp: dag(-1, 9, 0), verstuurdOp: dag(-1, 9, 5),
  },
  {
    id: "inv-3", nummer: "FACT-2026-0003", leadId: "lead-013",
    status: "verzonden",
    regels: [{ id: "ir1", omschrijving: "Prefab uitbouw — eindafrekening", aantal: 1, eenheid: "post", prijsPerStuk: 43000, btwPercentage: DEFAULT_BTW }],
    korting: 0, vervaldatum: dag(-12),
    aangemaaktOp: dag(-20, 10, 0), verstuurdOp: dag(-20, 10, 5),
  },
  {
    id: "inv-4", nummer: "FACT-2026-0004", leadId: "lead-014",
    status: "verzonden",
    regels: [{ id: "ir1", omschrijving: "Mantelzorgwoning — slottermijn 10%", aantal: 1, eenheid: "post", prijsPerStuk: 9200, btwPercentage: DEFAULT_BTW }],
    korting: 0, vervaldatum: dag(-3),
    aangemaaktOp: dag(-9, 10, 0), verstuurdOp: dag(-9, 10, 5),
  },
];

export const seedPayments: Payment[] = [
  { id: "pay-1", invoiceId: "inv-1", bedrag: 39204, methode: "ideal", datum: dag(-5, 12, 0) },
  { id: "pay-3", invoiceId: "inv-3", bedrag: 52030, methode: "overboeking", datum: dag(-14, 9, 0) },
];
