// ============================================================================
// Dummy data ("seed") voor het prototype.
// ----------------------------------------------------------------------------
// Alles is verzonnen maar realistisch voor Prefab Select. De Zustand-store
// initialiseert hiermee; later vervangt Supabase deze seed.
// ============================================================================

import type {
  Appointment,
  Integration,
  Lead,
  Note,
  Quote,
  QuoteEmailLog,
  QuoteRequest,
  Task,
  UploadedFile,
} from "./types";
import { DEFAULT_BTW, DEFAULT_VOORWAARDEN } from "./constants";

// Datums relatief t.o.v. nu, zodat het dashboard altijd "levend" oogt.
function dag(offset: number, uur = 9, minuut = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  d.setHours(uur, minuut, 0, 0);
  return d.toISOString();
}

export const seedLeads: Lead[] = [
  {
    id: "lead-001",
    naam: "Familie De Vries",
    email: "devries@gmail.com",
    telefoon: "06-21345678",
    adres: "Molenweg 12",
    plaats: "Middelburg",
    postcode: "4331 AB",
    stage: "nieuwe_lead",
    source: "website_formulier",
    product: "mantelzorgwoning",
    waarde: 89000,
    kans: 20,
    toegewezenAan: "Kelly",
    tags: ["zeeland", "spoed"],
    bericht: "Wij zoeken een mantelzorgwoning voor mijn moeder, het liefst dit jaar nog.",
    aangemaaktOp: dag(-1, 14, 12),
    laatsteActiviteit: dag(-1, 14, 12),
    positie: 0,
  },
  {
    id: "lead-002",
    naam: "Jeroen Bakker",
    email: "j.bakker@outlook.com",
    telefoon: "06-44112233",
    plaats: "Goes",
    stage: "nieuwe_lead",
    source: "meta_ads",
    product: "tuinkantoor",
    waarde: 24000,
    kans: 15,
    toegewezenAan: "Tom",
    tags: ["thuiswerken"],
    bericht: "Interesse in een tuinkantoor van ca. 20m².",
    aangemaaktOp: dag(0, 8, 30),
    laatsteActiviteit: dag(0, 8, 30),
    positie: 1,
  },
  {
    id: "lead-003",
    naam: "Sandra Pietersen",
    email: "s.pietersen@ziggo.nl",
    telefoon: "06-19283746",
    plaats: "Vlissingen",
    stage: "offerte_aanvraag",
    source: "configurator",
    product: "prefab_aanbouw",
    waarde: 56000,
    kans: 35,
    toegewezenAan: "Kelly",
    tags: ["configurator"],
    bericht: "Configuratie afgerond: aanbouw 6x4m met dakraam.",
    aangemaaktOp: dag(-3, 11, 0),
    laatsteActiviteit: dag(-1, 9, 45),
    positie: 0,
  },
  {
    id: "lead-004",
    naam: "Bouwbedrijf Janssen BV",
    bedrijf: "Janssen Bouw",
    email: "info@janssenbouw.nl",
    telefoon: "0118-556677",
    plaats: "Terneuzen",
    stage: "offerte_aanvraag",
    source: "referral",
    product: "schuur",
    waarde: 41000,
    kans: 40,
    toegewezenAan: "Mark",
    tags: ["zakelijk", "b2b"],
    aangemaaktOp: dag(-4, 16, 20),
    laatsteActiviteit: dag(-2, 13, 0),
    positie: 1,
  },
  {
    id: "lead-005",
    naam: "Familie Mulder",
    email: "mulder.familie@gmail.com",
    telefoon: "06-55667788",
    plaats: "Kapelle",
    stage: "gebeld",
    source: "google_ads",
    product: "poolhouse",
    waarde: 72000,
    kans: 45,
    toegewezenAan: "Sanne",
    tags: ["premium"],
    aangemaaktOp: dag(-6, 10, 0),
    laatsteActiviteit: dag(-1, 15, 30),
    positie: 0,
  },
  {
    id: "lead-006",
    naam: "Peter van Damme",
    email: "pvandamme@kpnmail.nl",
    telefoon: "06-33221100",
    plaats: "Zierikzee",
    stage: "gebeld",
    source: "website_formulier",
    product: "prefab_uitbouw",
    waarde: 38000,
    kans: 40,
    toegewezenAan: "Tom",
    tags: [],
    aangemaaktOp: dag(-8, 9, 0),
    laatsteActiviteit: dag(-2, 11, 15),
    positie: 1,
  },
  {
    id: "lead-007",
    naam: "Familie El Amrani",
    email: "elamrani@gmail.com",
    telefoon: "06-77889900",
    plaats: "Bergen op Zoom",
    stage: "afspraak_ingepland",
    source: "meta_ads",
    product: "mantelzorgwoning",
    waarde: 95000,
    kans: 55,
    toegewezenAan: "Kelly",
    tags: ["spoed", "premium"],
    aangemaaktOp: dag(-10, 12, 0),
    laatsteActiviteit: dag(0, 9, 0),
    positie: 0,
  },
  {
    id: "lead-008",
    naam: "Linda Hoogendoorn",
    email: "l.hoogendoorn@hotmail.com",
    telefoon: "06-12121212",
    plaats: "Roosendaal",
    stage: "afspraak_ingepland",
    source: "configurator",
    product: "chalet",
    waarde: 64000,
    kans: 50,
    toegewezenAan: "Sanne",
    tags: ["recreatie"],
    aangemaaktOp: dag(-12, 14, 0),
    laatsteActiviteit: dag(-1, 16, 0),
    positie: 1,
  },
  {
    id: "lead-009",
    naam: "Familie Smit",
    email: "smit.recreatie@gmail.com",
    telefoon: "06-98765432",
    plaats: "Renesse",
    stage: "offerte_verstuurd",
    source: "website_formulier",
    product: "vakantiewoning",
    waarde: 118000,
    kans: 60,
    toegewezenAan: "Mark",
    tags: ["recreatie", "premium"],
    aangemaaktOp: dag(-15, 10, 0),
    laatsteActiviteit: dag(-2, 10, 30),
    positie: 0,
  },
  {
    id: "lead-010",
    naam: "Karin de Groot",
    email: "kdegroot@gmail.com",
    telefoon: "06-45454545",
    plaats: "Tholen",
    stage: "offerte_verstuurd",
    source: "google_ads",
    product: "prefab_aanbouw",
    waarde: 49000,
    kans: 55,
    toegewezenAan: "Kelly",
    tags: [],
    aangemaaktOp: dag(-18, 9, 30),
    laatsteActiviteit: dag(-3, 14, 0),
    positie: 1,
  },
  {
    id: "lead-011",
    naam: "Familie Visser",
    email: "visser@home.nl",
    telefoon: "06-32132132",
    plaats: "Breda",
    stage: "akkoord",
    source: "referral",
    product: "poolhouse",
    waarde: 81000,
    kans: 90,
    toegewezenAan: "Sanne",
    tags: ["premium"],
    aangemaaktOp: dag(-25, 11, 0),
    laatsteActiviteit: dag(-1, 11, 0),
    positie: 0,
  },
  {
    id: "lead-012",
    naam: "Robert Maas",
    email: "r.maas@gmail.com",
    telefoon: "06-65656565",
    plaats: "Oosterhout",
    stage: "in_productie",
    source: "configurator",
    product: "tuinkantoor",
    waarde: 28000,
    kans: 100,
    toegewezenAan: "Tom",
    tags: ["thuiswerken"],
    aangemaaktOp: dag(-40, 10, 0),
    laatsteActiviteit: dag(-4, 9, 0),
    positie: 0,
  },
  {
    id: "lead-013",
    naam: "Familie Koning",
    email: "koning.familie@gmail.com",
    telefoon: "06-78787878",
    plaats: "Etten-Leur",
    stage: "geplaatst",
    source: "website_formulier",
    product: "prefab_uitbouw",
    waarde: 43000,
    kans: 100,
    toegewezenAan: "Mark",
    tags: [],
    aangemaaktOp: dag(-60, 10, 0),
    laatsteActiviteit: dag(-7, 12, 0),
    positie: 0,
  },
  {
    id: "lead-014",
    naam: "Familie Willems",
    email: "willems@xs4all.nl",
    telefoon: "06-90909090",
    plaats: "Goes",
    stage: "gewonnen",
    source: "meta_ads",
    product: "mantelzorgwoning",
    waarde: 92000,
    kans: 100,
    toegewezenAan: "Kelly",
    tags: ["premium", "review"],
    aangemaaktOp: dag(-80, 10, 0),
    laatsteActiviteit: dag(-10, 12, 0),
    positie: 0,
  },
  {
    id: "lead-015",
    naam: "Henk Dijkstra",
    email: "h.dijkstra@gmail.com",
    telefoon: "06-10101010",
    plaats: "Hulst",
    stage: "verloren",
    source: "google_ads",
    product: "chalet",
    waarde: 58000,
    kans: 0,
    toegewezenAan: "Sanne",
    tags: ["budget"],
    bericht: "Uiteindelijk voor een lokale aannemer gekozen.",
    aangemaaktOp: dag(-35, 10, 0),
    laatsteActiviteit: dag(-12, 9, 0),
    positie: 0,
  },
];

export const seedNotes: Note[] = [
  { id: "note-1", leadId: "lead-001", type: "systeem", tekst: "Lead aangemaakt via website formulier.", auteur: "Systeem", aangemaaktOp: dag(-1, 14, 12) },
  { id: "note-2", leadId: "lead-005", type: "telefoon", tekst: "Gebeld — wil graag de showroom bezoeken. Belt terug voor datum.", auteur: "Sanne", aangemaaktOp: dag(-1, 15, 30) },
  { id: "note-3", leadId: "lead-007", type: "telefoon", tekst: "Intakegesprek gepland voor volgende week. Zeer geïnteresseerd, budget akkoord.", auteur: "Kelly", aangemaaktOp: dag(0, 9, 0) },
  { id: "note-4", leadId: "lead-009", type: "email", tekst: "Offerte verstuurd via Resend. Klant bevestigt ontvangst.", auteur: "Mark", aangemaaktOp: dag(-2, 10, 30) },
  { id: "note-5", leadId: "lead-011", type: "notitie", tekst: "Akkoord op offerte! Aanbetaling 30% afgesproken. Productie kan starten zodra vergunning rond is.", auteur: "Sanne", aangemaaktOp: dag(-1, 11, 0) },
];

export const seedTasks: Task[] = [
  { id: "task-1", leadId: "lead-001", titel: "Familie De Vries terugbellen", omschrijving: "Eerste contact, behoefte inventariseren", vervaldatum: dag(0, 11, 0), prioriteit: "hoog", toegewezenAan: "Kelly", voltooid: false, reminderMinuten: 30 },
  { id: "task-2", leadId: "lead-003", titel: "Offerte opstellen aanbouw", vervaldatum: dag(1, 9, 0), prioriteit: "normaal", toegewezenAan: "Kelly", voltooid: false, reminderMinuten: 60 },
  { id: "task-3", leadId: "lead-005", titel: "Showroomafspraak inplannen", vervaldatum: dag(-1, 16, 0), prioriteit: "normaal", toegewezenAan: "Sanne", voltooid: false, reminderMinuten: null },
  { id: "task-4", leadId: "lead-009", titel: "Offerte opvolgen — bellen", omschrijving: "Offerte staat 2 dagen open", vervaldatum: dag(1, 14, 0), prioriteit: "hoog", toegewezenAan: "Mark", voltooid: false, reminderMinuten: 15 },
  { id: "task-5", leadId: "lead-012", titel: "Productieplanning bevestigen", vervaldatum: dag(3, 10, 0), prioriteit: "normaal", toegewezenAan: "Tom", voltooid: false, reminderMinuten: null },
  { id: "task-6", leadId: "lead-011", titel: "Aanbetaling factureren", vervaldatum: dag(2, 9, 0), prioriteit: "hoog", toegewezenAan: "Sanne", voltooid: false, reminderMinuten: 60 },
  { id: "task-7", titel: "Wekelijkse pipeline-review met team", vervaldatum: dag(2, 16, 0), prioriteit: "laag", toegewezenAan: "Kelly", voltooid: false, reminderMinuten: null },
  { id: "task-8", leadId: "lead-014", titel: "Review vragen aan familie Willems", vervaldatum: dag(-2, 10, 0), prioriteit: "laag", toegewezenAan: "Kelly", voltooid: true, reminderMinuten: null },
];

export const seedAppointments: Appointment[] = [
  { id: "afspr-1", leadId: "lead-007", titel: "Intake familie El Amrani", type: "intake", start: dag(2, 10, 0), eind: dag(2, 11, 0), locatie: "Bij klant thuis, Bergen op Zoom", notitie: "Mantelzorgwoning bespreken", googleSynced: true },
  { id: "afspr-2", leadId: "lead-008", titel: "Showroombezoek Linda Hoogendoorn", type: "showroom", start: dag(3, 14, 0), eind: dag(3, 15, 30), locatie: "Showroom Prefab Select", googleSynced: true },
  { id: "afspr-3", leadId: "lead-011", titel: "Locatiebezoek familie Visser", type: "locatiebezoek", start: dag(5, 9, 0), eind: dag(5, 11, 0), locatie: "Breda", notitie: "Opmeten + grond inspecteren", googleSynced: false },
  { id: "afspr-4", leadId: "lead-013", titel: "Oplevering familie Koning", type: "oplevering", start: dag(7, 13, 0), eind: dag(7, 14, 0), locatie: "Etten-Leur", googleSynced: true },
  { id: "afspr-5", leadId: "lead-005", titel: "Showroom familie Mulder", type: "showroom", start: dag(1, 11, 0), eind: dag(1, 12, 0), locatie: "Showroom Prefab Select", googleSynced: false },
];

export const seedFiles: UploadedFile[] = [
  { id: "file-1", leadId: "lead-003", naam: "configuratie-aanbouw.pdf", type: "pdf", grootteKb: 842, geuploadOp: dag(-3, 11, 5), geuploadDoor: "Systeem" },
  { id: "file-2", leadId: "lead-009", naam: "offerte-PS-2026-0009.pdf", type: "pdf", grootteKb: 1240, geuploadOp: dag(-2, 10, 30), geuploadDoor: "Mark" },
  { id: "file-3", leadId: "lead-011", naam: "situatieschets-tuin.jpg", type: "afbeelding", grootteKb: 3120, geuploadOp: dag(-5, 14, 0), geuploadDoor: "Sanne" },
  { id: "file-4", leadId: "lead-011", naam: "vergunning-aanvraag.pdf", type: "pdf", grootteKb: 560, geuploadOp: dag(-3, 9, 0), geuploadDoor: "Sanne" },
];

export const seedQuoteRequests: QuoteRequest[] = [
  { id: "aanvr-1", leadId: "lead-003", source: "configurator", product: "prefab_aanbouw", omschrijving: "Aanbouw 6x4m met plat dak en groot dakraam, inclusief afwerking keukenblok.", budgetIndicatie: 55000, gewensteOpleverdatum: dag(120), status: "in_behandeling", ontvangenOp: dag(-3, 11, 0) },
  { id: "aanvr-2", leadId: "lead-004", source: "referral", product: "schuur", omschrijving: "Bedrijfsschuur 10x6m voor opslag materiaal.", budgetIndicatie: 40000, status: "in_behandeling", ontvangenOp: dag(-4, 16, 20) },
  { id: "aanvr-3", leadId: "lead-002", source: "meta_ads", product: "tuinkantoor", omschrijving: "Tuinkantoor ca. 20m², geïsoleerd, met elektra.", budgetIndicatie: 24000, status: "nieuw", ontvangenOp: dag(0, 8, 30) },
  { id: "aanvr-4", leadId: "lead-009", source: "website_formulier", product: "vakantiewoning", omschrijving: "Recreatiewoning ca. 60m² voor verhuur in Renesse.", budgetIndicatie: 115000, status: "omgezet", ontvangenOp: dag(-15, 10, 0) },
  { id: "aanvr-5", leadId: "lead-001", source: "website_formulier", product: "mantelzorgwoning", omschrijving: "Mantelzorgwoning voor moeder, gelijkvloers, ca. 50m².", budgetIndicatie: 89000, gewensteOpleverdatum: dag(180), status: "nieuw", ontvangenOp: dag(-1, 14, 12) },
];

export const seedQuotes: Quote[] = [
  {
    id: "quote-1",
    nummer: "PS-2026-0009",
    leadId: "lead-009",
    status: "verstuurd",
    projecttype: "vakantiewoning",
    projectomschrijving: "Recreatiewoning voor verhuur op een park in Renesse. Energiezuinige prefab woning, instapklaar opgeleverd.",
    afmetingen: "10 x 6 m, vloeroppervlak ca. 60 m², nokhoogte 4,5 m",
    werkzaamheden: "Productie casco, transport, plaatsing op bestaande fundering, complete afwerking interieur en aansluiten installaties.",
    regels: [
      { id: "r1", omschrijving: "Vakantiewoning prefab casco 60m²", aantal: 1, eenheid: "stuks", prijsPerStuk: 78000, btwPercentage: DEFAULT_BTW },
      { id: "r2", omschrijving: "Complete afwerking interieur", aantal: 1, eenheid: "post", prijsPerStuk: 24000, btwPercentage: DEFAULT_BTW },
      { id: "r3", omschrijving: "Fundering & plaatsing", aantal: 1, eenheid: "post", prijsPerStuk: 12000, btwPercentage: DEFAULT_BTW },
    ],
    korting: 0,
    geldigTot: dag(25),
    notitie: "Levertijd ca. 16 weken na akkoord en vergunning.",
    voorwaarden: DEFAULT_VOORWAARDEN,
    aangemaaktOp: dag(-3, 10, 0),
    verstuurdOp: dag(-2, 10, 30),
  },
  {
    id: "quote-2",
    nummer: "PS-2026-0010",
    leadId: "lead-010",
    status: "bekeken",
    projecttype: "prefab_aanbouw",
    projectomschrijving: "Aanbouw aan de achterzijde van de woning ter vergroting van de woonkamer.",
    afmetingen: "5 x 4 m, vloeroppervlak 20 m², plat dak",
    werkzaamheden: "Productie en plaatsing prefab aanbouw casco, dakraam, isolatie en afwerking.",
    regels: [
      { id: "r1", omschrijving: "Prefab aanbouw 5x4m casco", aantal: 1, eenheid: "stuks", prijsPerStuk: 34000, btwPercentage: DEFAULT_BTW },
      { id: "r2", omschrijving: "Dakraam + extra isolatie", aantal: 1, eenheid: "post", prijsPerStuk: 6500, btwPercentage: DEFAULT_BTW },
      { id: "r3", omschrijving: "Plaatsing & afwerking", aantal: 1, eenheid: "post", prijsPerStuk: 8500, btwPercentage: DEFAULT_BTW },
    ],
    korting: 1000,
    geldigTot: dag(22),
    voorwaarden: DEFAULT_VOORWAARDEN,
    aangemaaktOp: dag(-4, 9, 0),
    verstuurdOp: dag(-3, 14, 0),
    bekekenOp: dag(-2, 18, 12),
  },
  {
    id: "quote-3",
    nummer: "PS-2026-0011",
    leadId: "lead-011",
    status: "geaccepteerd",
    projecttype: "poolhouse",
    projectomschrijving: "Vrijstaand poolhouse met overkapping en technische ruimte naast het zwembad.",
    afmetingen: "8 x 5 m, vloeroppervlak 40 m², incl. overkapping 3 m",
    werkzaamheden: "Productie, transport, fundering, plaatsing, sanitair en technische ruimte volledig aangesloten.",
    planning: "Start productie ca. 4 weken na akkoord · plaatsing in week 12 · oplevering in week 14 (indicatief, onder voorbehoud van vergunning).",
    regels: [
      { id: "r1", omschrijving: "Poolhouse 8x5m incl. overkapping", aantal: 1, eenheid: "stuks", prijsPerStuk: 62000, btwPercentage: DEFAULT_BTW },
      { id: "r2", omschrijving: "Sanitair & technische ruimte", aantal: 1, eenheid: "post", prijsPerStuk: 14000, btwPercentage: DEFAULT_BTW },
      { id: "r3", omschrijving: "Plaatsing & fundering", aantal: 1, eenheid: "post", prijsPerStuk: 9000, btwPercentage: DEFAULT_BTW },
    ],
    korting: 4000,
    geldigTot: dag(10),
    notitie: "Aanbetaling 30% bij akkoord.",
    voorwaarden: DEFAULT_VOORWAARDEN,
    aangemaaktOp: dag(-7, 11, 0),
    verstuurdOp: dag(-6, 9, 0),
    bekekenOp: dag(-5, 20, 0),
    beslistOp: dag(-1, 11, 0),
  },
];

export const seedEmailLogs: QuoteEmailLog[] = [
  { id: "mail-1", quoteId: "quote-1", naar: "smit.recreatie@gmail.com", onderwerp: "Uw offerte van Prefab Select", status: "verzonden", messageId: "seed-0009", mock: true, verstuurdOp: dag(-2, 10, 30) },
  { id: "mail-2", quoteId: "quote-2", naar: "kdegroot@gmail.com", onderwerp: "Uw offerte van Prefab Select", status: "verzonden", messageId: "seed-0010", mock: true, verstuurdOp: dag(-3, 14, 0) },
  { id: "mail-3", quoteId: "quote-3", naar: "visser@home.nl", onderwerp: "Uw offerte van Prefab Select", status: "verzonden", messageId: "seed-0011", mock: true, verstuurdOp: dag(-6, 9, 0) },
];

export const seedIntegrations: Integration[] = [
  { id: "int-meta", naam: "Meta Ads", categorie: "marketing", verbonden: false, beschrijving: "Importeer leads & advertentieprestaties uit Facebook/Instagram." },
  { id: "int-ga", naam: "Google Analytics 4", categorie: "analytics", verbonden: false, beschrijving: "Websiteverkeer, conversies en bronnen koppelen." },
  { id: "int-gcal", naam: "Google Calendar", categorie: "agenda", verbonden: false, beschrijving: "Afspraken automatisch synchroniseren met je agenda." },
  { id: "int-resend", naam: "Resend", categorie: "email", verbonden: false, beschrijving: "Offertes en e-mails versturen vanuit het CRM." },
  { id: "int-form", naam: "Website formulier", categorie: "website", verbonden: true, beschrijving: "Contact- en offerteformulieren van prefabselect.nl.", laatsteSync: dag(0, 8, 30) },
  { id: "int-config", naam: "Configurator", categorie: "website", verbonden: true, beschrijving: "Leads uit de online product-configurator.", laatsteSync: dag(-1, 9, 45) },
];
